# Generated by Django 6.0.7 on 2026-08-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('name', models.CharField(max_length=1, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='prefered_shifts',
            field=models.ManyToManyField(to='schedule.shift'),
        ),
    ]
