# Generated by Django 6.0.7 on 2026-08-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_shift_member_prefered_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='prefered_shifts',
        ),
        migrations.AddField(
            model_name='shift',
            name='long_name',
            field=models.CharField(default='toto', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ShiftPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_preferences', to='schedule.member')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.shift')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('date__isnull', True), ('weekday__isnull', True), _connector='OR'), name='date_or_weekday_not_both')],
            },
        ),
    ]
